name: ezmp
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  dotenv: ^3.0.0
  eanic: ^0.2.0
  spotify: ^0.7.0
  youtube_explode_dart: ^1.10.9+1
